### ISSUE TITLE
Can provide GIT model for TextVQA?

### ISSUE THREAD

**Issue by soonchangAI** [microsoft/GenerativeImage2Text#11]
Hi, thank you for your great work! Is the GIT model which manages to achieve 59.75% test accuracy for TextVQA in Table 3 provided?

**Comment by amsword** [comment]
The released models here are the base and the large versions of the GIT models. The details are described in the supplementary materials Table 15.

**Comment by soonchangAI** [comment]
@amsword Owh i see. Can u guys provide the regular GIT model for TextVQA?

**Comment by amsword** [comment]
@soonchangAI added the checkpoint for GIT_BASE_TEXTVQA and GIT_LARGE_TEXTVQA
