### ISSUE TITLE
Use of GIT model in a jupyter notebook?

### ISSUE THREAD

**Issue by ColinConwell** [microsoft/GenerativeImage2Text#14]
Thank you for your amazing work on the GIT model.

Is there any chance you might be willing to provide a minimal set of code to load and run the various kinds of model inference in a jupyter notebook?

Thank you in advance!

**Comment by amsword** [comment]
is there any issue to run, e.g. the following command according to the readme?

```bash
AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_image', \
      'image_path': 'aux_data/images/1.jpg', \
      'model_name': 'GIT_BASE', \
      'prefix': '', \
}"
```

**Comment by ColinConwell** [comment]
It would be nice to be able to explore model weights, and set up a more straightforward pipeline for captioning multiple images (as opposed to just multiple frames of a video).

**Comment by amsword** [comment]
@ColinConwell to explore the model weights, please change the value of `model_name` in the examples. To caption on multiple images, please call that example command line multiple times, or to update the code to incorporate some efficient data loader for faster speed. Please feel free to post any difficulty to set it up.
