### ISSUE TITLE
lineidx for custom TSV file

### ISSUE THREAD

**Issue by jecummin** [microsoft/GenerativeImage2Text#16]
Thank you for your great work on this model and repo.

I'm trying to use this model to caption some of my own images and created an image TSV file as described in the README.md with two columns, one with the image key and one with the encoded byte string. However, when I run the example single TSV command with my own tsv file, entitled `my_images.tsv` , I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'my_images.lineidx'
```

What is the `lineidx` mean here? Evidently, there is something else that I need to include in order for the model to run on my TSV but I can't find any information about it in the repo. What else do I need to do?

**Comment by amsword** [comment]
To generate tsv data, please use the following function
https://github.com/microsoft/GenerativeImage2Text/blob/b22f8e3b5ab1c14815abf90759d1cefe1c307753/generativeimage2text/tsv_io.py#L356


Some examples to use this function: https://github.com/microsoft/GenerativeImage2Text/blob/b22f8e3b5ab1c14815abf90759d1cefe1c307753/generativeimage2text/data_prepare.py#L40


The lineidx file tells the byte offset for each line, such that it can support random seeking. Feel free to re-open it for any other questions.
