### ISSUE TITLE
Chinese caption

### ISSUE THREAD

**Issue by Carlos25130** [microsoft/GenerativeImage2Text#18]
Thank you for your work！Is it possible for you to release the Chinese caption model later？Or could you give me some suggestions on Chinese caption？ Thank you very much.

**Comment by amsword** [comment]
currently, it is English-only model. To have other languages, you may need to train the model with your own dedicated dataset (with image/Chinease description pairs). The only code you may need to pay attention to is the tokenizer. That is, change it to a tokenizer which supports Chinese. All other code/ideas should be similar.

**Comment by Carlos25130** [comment]
Thank you very much!



---- Replied Message ----
| From | Jianfeng ***@***.***> |
| Date | 10/29/2022 03:20 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [microsoft/GenerativeImage2Text] Chinese caption (Issue #18) |

currently, it is English-only model. To have other languages, you may need to train the model with your own dedicated dataset (with image/Chinease description pairs). The only code you may need to pay attention to is the tokenizer. That is, change it to a tokenizer which supports Chinese. All other code/ideas should be similar.
