### ISSUE TITLE
About generation results.

### ISSUE THREAD

**Issue by victorup** [microsoft/GenerativeImage2Text#19]
Hi, 

When I use GIT_LARGE_COCO to generate captions, the results show many "[ unused0 ]" tokens in the captions.  
For example: 
- "[ unused0 ]'s [ unused0 ]'s [ unused0 ]". 
- "[ unused0 ] in a scene from the movie ` ` [ unused0 ]''"

So what is "[ unused0 ]"? Does it mean an unknown word? 
Why it generates many "[ unused0 ]" tokens?  
How could I avoid these situations?

Thanks!

**Comment by amsword** [comment]
can you first try the image shared in the readme and see if there is still such [unused0]? In the meanwhile, can you also share the image you are trying to test? I can test it on my side for further investigation.

**Comment by victorup** [comment]
The caption of the image in the readme can be generated very well.
Sorry, I'm not convenient to share the images. But I further checked my testset, and find that the "[ unused0 ]" tokens usually appear when there is any strange object. So I think the token may mean an unknown word. 
I will clean my data for better results.
Thank you!

**Comment by prashantkandel12** [comment]
I've got the same issue and i can paste that image with caption
![image](https://user-images.githubusercontent.com/30668506/200575950-1bb839e2-2405-4d02-b92c-cc29bb06b40d.png)

the output is :  [unused0] sticking his tongue out

**Comment by amsword** [comment]
Thanks for reporting this. We will investigate more on this issue. I tried the base-version, which can give reasonable results.

**Comment by amsword** [comment]
In CC12M, the person's name is replaced as \<PERSON\>, while here [unused0] is used to replace such special token. CC12M is used in LARGE model, but not in BASE model. [unused0] can be re-interpreted as _a person_

Original CC12M data examples:
```
['The source of Anime quotes & Manga quotes : Photo <PERSON>, Manga Quotes, '
 'Art Images, Fan Art, Thoughts, Think, Anime, Crying, Random\n',
 '<PERSON> with Bindi, <PERSON> and <PERSON> before he left the zoo, and lost '
 "contact with his late son's family. Photo: Getty Images\n",
 'The wedding of <PERSON> and Ashleigh McDonald Photography 11\n',
 'An artist rendering shows Supreme Court Justices from left, <PERSON>, '
 '<PERSON>, <PERSON>, <PERSON>, Chief Justice <PERSON>, <PERSON>, <PERSON>, '
 '<PERSON>, and <PERSON> inside Supreme Court in W\n',
 "'(Day 10) <PERSON>'s team clinches the BAT Grad Academy's 'Best Place to "
 "Work For' award at the business simulation!'' Do you aspire to work in top "
 'global company? Look no further. BAT is well known for being one of the '
 "world's best companies to work at, certified as a Top Employer around the "
 'world. BAT Malaysia has also won several HR excellence awards, leading in '
 'several categories including Employee Engagement and Best Companies to Work '
 'for in Asia. This is testament to the initiatives and efforts invested into '
 "their people agenda.'\n"]
```

cc12M paper
![image](https://user-images.githubusercontent.com/3356680/200662001-87e0cd1f-aca0-4fa0-b048-cce48b9de767.png)

**Comment by prashantkandel12** [comment]
Thank you for the answer. Results were same for me too base model had no issues but large model gave me these results.

**Comment by DDuan-zw** [comment]
anyway to solve it?

**Comment by amsword** [comment]
one way is to retrain the large model by not using such special characters. I will try to do this.

**Comment by prashantkandel12** [comment]
I have noticed another interesting thing with the generation results:
It is giving same output "digital art selected for the #" 
for all of the following images:
All of these images were generated by using stable diffusion.
![image](https://user-images.githubusercontent.com/30668506/205530940-666b5129-1d09-451e-a667-a26340da02e8.png)
![image](https://user-images.githubusercontent.com/30668506/205530959-a6bf94e4-0a75-4472-bc7f-b54d2a61bdda.png)
![image](https://user-images.githubusercontent.com/30668506/205530968-974ba063-6ae1-483d-9306-e08ac6fb64ff.png)
![image](https://user-images.githubusercontent.com/30668506/205531013-b545df74-1a1c-4a8f-af4e-619cc34933b9.png)
![image](https://user-images.githubusercontent.com/30668506/205531066-f7ad2f9c-47af-4e70-b69d-6428a6965571.png)
![image](https://user-images.githubusercontent.com/30668506/205531104-e5fcc06d-4573-44fd-97b7-856b705c2620.png)
![image](https://user-images.githubusercontent.com/30668506/205531238-02e9f03f-24ef-4547-8e43-7f7191c3bfc6.png)

**Comment by amsword** [comment]
@prashantkandel12  @DDuan-zw I removed the offensive captions in cc12m dataset and retrained the large-sized model. Please check the details here. 

For the image of Einstein, the model of GIT_LARGE_R_COCO will predict: ‘a black and white photo of a man sticking his tongue out.’. 

![image](https://user-images.githubusercontent.com/3356680/211131205-59bda932-80b0-4e7b-8ec0-5013f64ef726.png)

**Comment by amsword** [comment]
> I have noticed another interesting thing with the generation results: It is giving same output "digital art selected for the #" for all of the following images: All of these images were generated by using stable diffusion. ![image](https://user-images.githubusercontent.com/30668506/205530940-666b5129-1d09-451e-a667-a26340da02e8.png) ![image](https://user-images.githubusercontent.com/30668506/205530959-a6bf94e4-0a75-4472-bc7f-b54d2a61bdda.png) ![image](https://user-images.githubusercontent.com/30668506/205530968-974ba063-6ae1-483d-9306-e08ac6fb64ff.png) ![image](https://user-images.githubusercontent.com/30668506/205531013-b545df74-1a1c-4a8f-af4e-619cc34933b9.png) ![image](https://user-images.githubusercontent.com/30668506/205531066-f7ad2f9c-47af-4e70-b69d-6428a6965571.png) ![image](https://user-images.githubusercontent.com/30668506/205531104-e5fcc06d-4573-44fd-97b7-856b705c2620.png) ![image](https://user-images.githubusercontent.com/30668506/205531238-02e9f03f-24ef-4547-8e43-7f7191c3bfc6.png)

@prashantkandel12 I tried the model of GIT_LARGE_COCO, the output is as follows. I assume you were using the pretrained model. For a demo purpose, it is recommended to use the fine-tuned ones as the pretraining dataset is quite noisy. 

3d rendering of a woman wearing a virtual reality headset.
