### ISSUE TITLE
Individual caption for individual frames

### ISSUE THREAD

**Issue by prashantkandel12** [microsoft/GenerativeImage2Text#23]
Currently when you supply multiple images it treats them as frames of video.  I want to know if there any way to generate captions for multiple images individually.
**example** 
**Input**
```
 'image_path': ['aux_data/images/1.jpg', 'aux_data/images/2.jpg', 'aux_data/images/1.jpg', 'aux_data/images/2.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg'],
```
**current output** : Single caption for all frames combined

```
clouds in the sky
```
**What i want** : Individual caption for individual frames
```
a large body of water
Cloud in the sky
a large body of water
Cloud in the sky
```

Using for loops in shell can be the solution but it will load and unload the model everytime which makes the task slower.

**Comment by amsword** [comment]
For this issue, within the repo, there is no ready-to-use code path. But it should be easy to run inference on multiple images as there is one example to run on one image. For example of the following function, you can go through all image files and only initialize the model once.

https://github.com/microsoft/GenerativeImage2Text/blob/777860e0660de1f80d4a9cd8f71a92f9b83bc514/generativeimage2text/inference.py#L67

**Comment by muxizju** [comment]
> 
does the code support for batch inference?

**Comment by amsword** [comment]
I have not tested it yet for the batch inference; but it should be easy to do as all input images are resized to the same resolution. it is straightforard to run the batch version.
