### ISSUE TITLE
Question about the number of image features(embeddings) projected into the input to text decoder.

### ISSUE THREAD

**Issue by dlwogns0128** [microsoft/GenerativeImage2Text#27]
Hi, I read paper and checked the code about the number of image features projected into the input to text decoder. 
Is it right the only feature of [CLS] token from Vision Transformer used to be projected into the input to text decoder?
And then, Does text decoder decode with the only one token of projected image features and others tokens of text features?

https://github.com/microsoft/GenerativeImage2Text/blob/777860e0660de1f80d4a9cd8f71a92f9b83bc514/generativeimage2text/layers/CLIP/model.py#L270

Thanks about your nice research!

**Comment by amsword** [comment]
no. output_grid will be true in this case

https://github.com/microsoft/GenerativeImage2Text/blob/777860e0660de1f80d4a9cd8f71a92f9b83bc514/generativeimage2text/layers/CLIP/model.py#L263

**Comment by bexxnaz** [comment]
Hi, When fine-tuning a GIT-based model on video domain using the code provided, should the input sizes for image and video features be identical? Currently, the image input size is [1,197,768] and the video input size is [1,1182,768] for the text decoder.
