### ISSUE TITLE
Question about character [unused]

### ISSUE THREAD

**Issue by Song-WenPo** [microsoft/GenerativeImage2Text#29]
I use model GIT_LARGE_COCO to test caption on an image https://wx4.sinaimg.cn/mw2000/632a985cly1fi3b3qohw2j210d1jktcr.jpg use bash command 
CUDA_VISIBLE_DEVICES=1 AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_image', \
      'image_path': './Images/Characters_and_celebrities-Angelina_Jolie4.jpg', \
      'model_name': 'GIT_LARGE_COCO', \
      'prefix': '', \
}"

But we got a caption:  ##0 ] as [ unused0 ] in ` ` the twilight zone'' [ unused0 ], [ unused0 ], [ unused0 ], [ unused0 ], [ unused0]
And this happened on some other images too, why this happen?

**Comment by DDuan-zw** [comment]
same here, I know it's problem of tokenize, but don't know how to fix it

**Comment by amsword** [comment]
duplicate of https://github.com/microsoft/GenerativeImage2Text/issues/19. will release another one once with it fixed.
