### ISSUE TITLE
About pretraining

### ISSUE THREAD

**Issue by victorup** [microsoft/GenerativeImage2Text#31]
Hi, 

The pretraining command in README.md is:
`python -m generativeimage2text.train -p "{'type': 'forward_backward_example', \
                'image_files': ['aux_data/images/1.jpg', 'aux_data/images/2.jpg'], \
                'captions': ['a couple of boats in a large body of water.', 'a view of a mountain with a tree'], \
            }"`

I would like to pretraining on my own datasets. I have checked the code in train.py and I find it doesn't divide batches of data for training and there is no optimizer to update the model. 
Would you provide codes for formal pretraining?

Thanks!

**Comment by amsword** [comment]
Based on that function, it should be easy to integrate it into any kind of trainer, e.g. deepspeed, ddp. Please feel free to pose any issues when you integrate it.
