### ISSUE TITLE
Inference for videos

### ISSUE THREAD

**Issue by XinhaoMei** [microsoft/GenerativeImage2Text#33]
Hi,

Thank you for your excellent work.

I have some videos, and want to generate captions for them. 
I now have generate 6 frames (images) for each video.
How can I run the inference for them.

For example, for inference code
`AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_tsv', \
      'image_tsv': 'data/coco_caption/test.img.tsv', \
      'model_name': 'GIT_BASE_COCO', \
      'question_tsv': null, \
      'out_tsv': 'inference/GIT_BASE_COCO/coco.tsv', \
}"`

Could you please let me know what the tsv file should  look like, and how to generate it?
Thanks in advance!

**Comment by NielsRogge** [comment]
Hi,

See #34 it will make your life easier ;)

**Comment by amsword** [comment]
@XinhaoMei your question context is about video, but the example code you posed here is about image. Please feel free to pose issues if you still have.
