### ISSUE TITLE
GIT_LARGE weights

### ISSUE THREAD

**Issue by FBehrad** [microsoft/GenerativeImage2Text#35]
When I was reading issues, I found this link to download GIT_BASE model:
https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt

Can you please provide a link for downloading GIT_LARGE model?

**Comment by amsword** [comment]
replace the keyword of GIT_BASE with the model name.

**Comment by donnadamus** [comment]
Hi, how do I download the model weights? 

https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt

Here I get PublicAccessNotPermitted
