### ISSUE TITLE
[Documentation Update] [Request] Tag "AZFUSE_TSV_USE_FUSE=1" needs further explanation

### ISSUE THREAD

**Issue by npapasta** [microsoft/GenerativeImage2Text#36]
Hi, thank you for posting this repository. It looks really interesting. I want to replicate the model results locally and compare them with those of Salesforce's LAVIS BLIP models. I am running into some issues with the "AZFUSE_TSV_USE_FUSE=1" tag. If possible, can you please add some more documentation on how to download and use azfuse?

**Comment by Zkli-hub** [comment]
HI! DID YOU SOLVE IT? I MET THE SAME PROBLEM
