### ISSUE TITLE
finetuning

### ISSUE THREAD

**Issue by nazar-karpov** [microsoft/GenerativeImage2Text#38]
am i able to finetune on custom dataset this model via GIT model on hugging face(video captioning task)

**Comment by amsword** [comment]
what is your question or issue? sorry, i do not get it.

**Comment by mbertini** [comment]
Is it possible to fine tune a model, e.g. the LARGE_VQA2 one ? How ?

**Comment by amsword** [comment]
Yes. The key code path is here

https://github.com/microsoft/GenerativeImage2Text#training
