### ISSUE TITLE
HELLO , FOR VQA task , your sample code generate None? could you help me

### ISSUE THREAD

**Issue by tangxiaochu123230** [microsoft/GenerativeImage2Text#4]

**Comment by tangxiaochu123230** [comment]
python -m generativeimage2text.train -p "{'type': 'forward_backward_example', \
                'image_files': ['aux_data/images/1.jpg', 'aux_data/images/2.jpg'], \
                'prefixs': ['what is this?', 'how many trees?'], \
                'captions': ['several boats in a large body of water', '1'], \
            }"

**Comment by tangxiaochu123230** [comment]
i miss the yaml file ?

**Comment by amsword** [comment]
what do you mean by None here? Based on the sample code, it is easy to figure out the data transformation and model structure. Then, you can embed it to any kind of trainer, e.g. deepspeed. The example here will only run one forward and one backward. It will not really train a model.
