### ISSUE TITLE
What is the best way to reduce the appearance of false positive text detection in captions using git-large-r-textcaps?

### ISSUE THREAD

**Issue by artificialguybr** [microsoft/GenerativeImage2Text#43]
I have noticed that while scene detection with GIT is very good, I am getting a large amount of text detection in images that have no text. Something in the range of 6% to 18% depending on the image set used.

I have looked at some of the templates and found some settings that could be used to try to mitigate this, but I would like to hear from people who may have already found a fix for this problem.

My main idea would be to decrease the aggressiveness of the text detection, but if not possible even exclude it completely.

I am using git-large-r-textcaps to do caption detection on images. Apart from this problem, I am having great results.

**Comment by anjum3** [comment]
Hi, Sorry me response is not related to your question. I am trying to train it on coco dataset for learning purposes. As you have already trained i checked that it is not proper tead file for beginners. Can you please how you provided dataset to train.py? I would be thankful to you.

**Comment by amsword** [comment]
@jvkap , try GIT_LARGE_R_COCO? This model normally will not read the scene text.

**Comment by artificialguybr** [comment]
> @jvkap , try GIT_LARGE_R_COCO? This model normally will not read the scene text.

@amsword This model is worse at describing scenes compared to GIT-LARGE-R-TEXTCAPS. It describes the image in a very simple way, while textcaps seems to go deeper and can explain the image in a more detailed way.
The only problem is that it seems to have a very fine text detection which makes it have a lot of false positives in situations that not have any text.

For example;
Image 1:
Textcaps: a book with a necklace and crystals on it and a book with the word " the word " on it ".
COCO:  a necklace made of glass and crystals

Image2:
TextCaps: soldiers in a dark scene with the words " army " on the front.
COCO: a soldier on fire in the night

Image 3:
TextCaps: a skull with a butterfly on it and the word " c " on the front.
COCO: the butterfly skull is a work of art by person.

Image 4: 
TextCaps: a girl's face underwater in the dark
COCO: a girl is underwater with the word " water " on the bottom.

**Comment by amsword** [comment]
would you mind sharing the image also? Also, for Image 4, is the result switched between TextCaps and COCO?

**Comment by artificialguybr** [comment]
> would you mind sharing the image also? Also, for Image 4, is the result switched between TextCaps and COCO?

Yes, I got it mixed up. I will redo the tests here and upload them. I did tests with 500 images. I will make two files one TEXTCAPS and one COCO and upload them as soon as I am done.
I also sent you an email

**Comment by artificialguybr** [comment]
@amsword

> would you mind sharing the image also? Also, for Image 4, is the result switched between TextCaps and COCO?

I sent you several examples in your e-mail. I will not send them here bc copyright reasons.

**Comment by amsword** [comment]
as the image is mainly out of domains, it is not easy for the base-sized or the large-sized model to predict meaningful results, although the vanilla GIT or GIT2 may give better results. One thing you may want to try is to fine-tune the base or large-sized models with annotations on the specific domains.
