### ISSUE TITLE
Question about ground-truth answers during fine-tuning on VQAv2

### ISSUE THREAD

**Issue by heendung** [microsoft/GenerativeImage2Text#45]
Hello,

Thanks for your stellar work and sharing your code!

I have a quick question. When you calculated the loss during fine-tuning on VQAv2, did you use **one** ground-truth answer as a target? If so, how did you choose one from ten ground-truth answers? Perhaps the one appears most frequently?

Thank you!

**Comment by amsword** [comment]
just randomly choose one of the answers. This is similar to how we choose the caption if one image has multiple captions.
