### ISSUE TITLE
About Fine-tuning on Video-QA dataset

### ISSUE THREAD

**Issue by Clement25** [microsoft/GenerativeImage2Text#46]
Hi, could you please share more settings during the fine-tuning GIT_base? The batch size and optimizer choices cannot be found in the appendix. Do you use the same setting as visual question answering (batch size=576)?

**Comment by amsword** [comment]
For GIT_BASE, Video-QA, the batch size is 512; epochs = 20; base-lr = 1e-5

**Comment by amsword** [comment]
similar to GIT.
