### ISSUE TITLE
Code for reproducing zero-shot ImageNet1K evaluation?

### ISSUE THREAD

**Issue by linzhiqiu** [microsoft/GenerativeImage2Text#47]
I was wondering whether you may release the code for ImageNet1K evaluation. Is it possible to release that or is there an existing code snippet that can achieve this?

**Comment by amsword** [comment]
evaluation? it is in the footnote 3 in the paper, as follows. 

3pred.replace(‘ ’, ‘’) == gt.replace(‘ ’, ‘’)
