### ISSUE TITLE
Question about Fine-tuning on Video

### ISSUE THREAD

**Issue by bexxnaz** [microsoft/GenerativeImage2Text#48]
Hi, I'm glad to see your excellent work.
When adapting a GIT-based model to the video domain using the provided code, is it necessary to ensure that the input sizes for both image and video features are the same? Specifically, the current image input size is [1,197,768] and the video input size is [1,1182,768] for the text decoder, but is it possible to generalize the image domain to the video domain without requiring identical input sizes?
Thank you！

**Comment by amsword** [comment]
I think so. In the current implementation (shown in the paper), the pretraining takes, e.g. 197 image features, but when applied in the video domain, the input can be a very large number of visual tokens. The transformer uses attention to fuse the visual signals. With more visual signals, the text output may pay more attention to the visual inputs, which is not that a problem. 

If you would like to reduce the number of video tokens, e.g. to be the same as the number of image tokens, you can have several options. For example, one is to randomly select some of video tokens. The other one could be the perceiver sampling shown in Deepmind's Flamingo paper, which would require a new pretraining.
