### ISSUE TITLE
error about azcopy

### ISSUE THREAD

**Issue by zhaomingheyuhan** [microsoft/GenerativeImage2Text#52]
Hello! When I run 
```
AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_image', \
      'image_path': 'aux_data/images/1.jpg', \
      'model_name': 'GIT_BASE', \
      'prefix': '', \
}"
```
The following error occurred. I'm not sure what the reason is, whether it was an error installing azfuse. If you could provide suggestions, I would greatly appreciate it.
![image](https://github.com/microsoft/GenerativeImage2Text/assets/68057146/0f50b09d-a3df-4027-8803-412c907fdef0)

![image](https://github.com/microsoft/GenerativeImage2Text/assets/68057146/2e4a46d6-ed72-44ca-a11a-3582847af7d8)

**Comment by amsword** [comment]
as your log shows, the error is following:
permission denied: /home/xxx/azcopy.

Thus, 
1.check if this azcopy file path can correctly localize your azcopy?
2. run the command tool and see if it is executible. make sure -x added to the azcopy file. (chmod +x /home/xxx/azcopy)
