### ISSUE TITLE
Setting for Zero-shot ImageNet classification

### ISSUE THREAD

**Issue by zfchenUnique** [microsoft/GenerativeImage2Text#53]
Hi, thanks for your great work!

Could you please provide your evaluation code for zero-shot imageNet classification?
More specifically, I would like to know how to implement "limit the candidate tokens during each token prediction, such that the predicted result is guaranteed to be within the vocabulary."
Thanks in advance.

Sincerely,
Zhenfang

**Comment by amsword** [comment]
That is based on a trie structure. I will try to find out some time to clean those codes.

**Comment by vishaal27** [comment]
Any update on this?

**Comment by amsword** [comment]
please uncomment the following to enable this decoding

https://github.com/microsoft/GenerativeImage2Text/blob/faae4fb9f34bfc2fce443513ae222e02b9f7e2e9/generativeimage2text/model.py#L42
