### ISSUE TITLE
Where can we download pretrained weights for Git MSVD-QA?

### ISSUE THREAD

**Issue by ee2110** [microsoft/GenerativeImage2Text#57]
Hi, thank you so much for the great work and releasing the code. I would like to study on videoQA ability of this model, specifically or MSVD-QA or TGIF-Frame, is that possible for us to download the fine-tuned or pre-trained weights so that we could use them for zero-shot on datasets? Thank you.

**Comment by hanranCode** [comment]
you can find model from huggingface.   eg: “git-base-vqav2” model   ->   https://huggingface.co/microsoft/git-base-vqav2

**Comment by amsword** [comment]
please re-open it for any other question.
