### ISSUE TITLE
 inference on single image

### ISSUE THREAD

**Issue by Carlos25130** [microsoft/GenerativeImage2Text#6]
when inference on single image

Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\azfuse\common.py", line 204, in limited_retry_agent
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'output/GIT_BASE/snapshot/model.pt'
Traceback (most recent call last):
  File "E:/REC/GenerativeImage2Text/inference.py", line 317, in <module>
    locals()[function_name](**kwargs)
  File "E:/REC/GenerativeImage2Text/inference.py", line 81, in test_git_inference_single_image
    checkpoint = torch_load(pretrained)['model']
  File "E:\REC\GenerativeImage2Text\generativeimage2text\torch_common.py", line 42, in torch_load
    with File.open(filename, 'rb') as fp:
  File "E:\Anaconda\lib\site-packages\azfuse\azfuse.py", line 52, in open
    return exclusive_open_to_read(fname, mode)
  File "E:\Anaconda\lib\site-packages\azfuse\common.py", line 113, in exclusive_open_to_read
    fp = limited_retry_agent(10, open, fname, mode)
  File "E:\Anaconda\lib\site-packages\azfuse\common.py", line 204, in limited_retry_agent
    return func(*args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'output/GIT_BASE/snapshot/model.pt'
2022-08-24 17:10:13,540.540 12420:common.py:209 limited_retry_agent(): fails with 
[Errno 2] No such file or directory: 'output/GIT_BASE/snapshot/model.pt': tried 10/10-th time

how to get the file 'output/GIT_BASE/snapshot/model.pt‘ ？

**Comment by amsword** [comment]
what is your command line to run the inference script? do you install the azfuse? have you enabled it through AZFUSE_TSV_USE_FUSE=1?

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/3356680/186531423-9238a60f-5543-44b9-a712-8467e52a7e4b.png">

**Comment by Carlos25130** [comment]
Thank you for your answer. I already know the problem. I run the code on Windows, so `AZFUSE_TSV_USE_FUSE=1` will fail.
But I don't know how to solve it

**Comment by Carlos25130** [comment]
> what is your command line to run the inference script? do you install the azfuse? have you enabled it through AZFUSE_TSV_USE_FUSE=1?
> 
> <img alt="image" width="1229" src="https://user-images.githubusercontent.com/3356680/186531423-9238a60f-5543-44b9-a712-8467e52a7e4b.png">
Thank you for your answer. I already know the problem. I run the code on Windows, so run the code`AZFUSE_TSV_USE_FUSE=1` in terminal will fail.
But I don't know how to solve it

**Comment by amsword** [comment]
on windows, you need to set the environment variable. One way is to search 'edit the environment' from start menu. I have not tested it on windows, but feel free to pose any issue you have.

**Comment by Carlos25130** [comment]
Thank you very much for your clarification before. Now I have been able to run the code smoothly, but when I ran the example code of a single image(image caption), the result was very unsatisfactory.
Do I need to write a complete training code for training?



At 2022-08-26 02:40:42, "Jianfeng Wang" ***@***.***> wrote:

on windows, you need to set the environment variable. One way is to search 'edit the environment' from start menu. I have not tested it on windows, but feel free to pose any issue you have.

**Comment by amsword** [comment]
Do you mean that the result of the example in the readme is unsatisfactory? Can you repost the command line you used and the captioning result here? One thing I’d like to confirm is we are on the same page of the quality

**Comment by Carlos25130** [comment]
I executed the following command


Then the result is too simplistic， the caption is “ the water is calm ”
















At 2022-08-30 15:21:31, "Jianfeng Wang" ***@***.***> wrote:

Do you mean that the result of the example in the readme is unsatisfactory? Can you repost the command line you used and the captioning result here? One thing I’d like to confirm is we are on the same page of the quality

**Comment by amsword** [comment]
I see. If you'd like to train the model, the key training code has already been in this repo. That is, how to do the data augmentation, and how to run forward/backward.

**Comment by Neleac** [comment]
@Carlos25130 How did you run this on Windows? I'm stuck on a ModuleNotFoundError for `fcntl`. Which apparently isn't supported on Windows? Here's my output:

$ AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_image',  'image_path': 'aux_data/images/1.jpg', 'model_name': 'GIT_BASE', 'prefix': ''}"
2022-09-18 19:58:30,062.062 39616:inference.py:318   <module>(): param:
{'image_path': 'aux_data/images/1.jpg',
 'model_name': 'GIT_BASE',
 'prefix': '',
 'type': 'test_git_inference_single_image'}
Traceback (most recent call last):
  File "C:\Users\Caelen\anaconda3\envs\git\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Caelen\anaconda3\envs\git\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Caelen\Desktop\GenerativeImage2Text\generativeimage2text\inference.py", line 321, in <module>
    locals()[function_name](**kwargs)
  File "C:\Users\Caelen\Desktop\GenerativeImage2Text\generativeimage2text\inference.py", line 69, in test_git_inference_single_image
    if File.isfile(f'aux_data/models/{model_name}/parameter.yaml'):
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\azfuse.py", line 39, in isfile
    cls.ensure_initialized()
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\azfuse.py", line 25, in ensure_initialized
    cls.fuser = create_cloud_fuse()
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\cloud_storage.py", line 155, in create_cloud_fuse
    config = load_from_yaml_file(fname)
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 259, in load_from_yaml_file
    with exclusive_open_to_read(file_name, 'r') as fp:
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 108, in exclusive_open_to_read
    lock_fd = acquireLock(op.join('/tmp',
  File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 181, in acquireLock
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by amsword** [comment]
duplicate of https://github.com/microsoft/GenerativeImage2Text/issues/12

**Comment by Carlos25130** [comment]
> 

There are indeed too many problems under windows, so I switched to Linux later. 
About the fcntl， I had the same problem before. My workaround is as follows：

Create the fcntl.py file in the Lib folder of the python installation directory you are using.
The contents of fcntl.py are as follows: 

#fcnt1.py
 
DN_ACCESS = 1
DN_ATTRIB = 32
DN_CREATE = 4
DN_DELETE = 8
DN_MODIFY = 2
DN_MULTISHOT = 2147483648
DN_RENAME = 16

FASYNC = 8192

FD_CLOEXEC = 1

F_ADD_SEALS = 1033

F_DUPFD = 0

F_DUPFD_CLOEXEC = 1030

F_EXLCK = 4
F_GETFD = 1
F_GETFL = 3
F_GETLEASE = 1025
F_GETLK = 5
F_GETLK64 = 5
F_GETOWN = 9
F_GETSIG = 11

F_GET_SEALS = 1034

F_NOTIFY = 1026
F_RDLCK = 0

F_SEAL_GROW = 4
F_SEAL_SEAL = 1
F_SEAL_SHRINK = 2
F_SEAL_WRITE = 8

F_SETFD = 2
F_SETFL = 4
F_SETLEASE = 1024
F_SETLK = 6
F_SETLK64 = 6
F_SETLKW = 7
F_SETLKW64 = 7
F_SETOWN = 8
F_SETSIG = 10
F_SHLCK = 8
F_UNLCK = 2
F_WRLCK = 1

LOCK_EX = 2
LOCK_MAND = 32
LOCK_NB = 4
LOCK_READ = 64
LOCK_RW = 192
LOCK_SH = 1
LOCK_UN = 8
LOCK_WRITE = 128

def fcntl(fd, op, arg=0):
    return 0

def ioctl(fd, op, arg=0, mutable_flag=True):
    if mutable_flag:
        return 0
    else:
        return ""

def flock(fd, op):
    return

def lockf(fd, operation, length=0, start=0, whence=0):
    return

**Comment by Carlos25130** [comment]
> @Carlos25130 How did you run this on Windows? I'm stuck on a ModuleNotFoundError for `fcntl`. Which apparently isn't supported on Windows? Here's my output:
> 
> $ AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p "{'type': 'test_git_inference_single_image', 'image_path': 'aux_data/images/1.jpg', 'model_name': 'GIT_BASE', 'prefix': ''}" 2022-09-18 19:58:30,062.062 39616:inference.py:318 (): param: {'image_path': 'aux_data/images/1.jpg', 'model_name': 'GIT_BASE', 'prefix': '', 'type': 'test_git_inference_single_image'} Traceback (most recent call last): File "C:\Users\Caelen\anaconda3\envs\git\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\Caelen\anaconda3\envs\git\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Caelen\Desktop\GenerativeImage2Text\generativeimage2text\inference.py", line 321, in locals()[function_name](**kwargs) File "C:\Users\Caelen\Desktop\GenerativeImage2Text\generativeimage2text\inference.py", line 69, in test_git_inference_single_image if File.isfile(f'aux_data/models/{model_name}/parameter.yaml'): File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\azfuse.py", line 39, in isfile cls.ensure_initialized() File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\azfuse.py", line 25, in ensure_initialized cls.fuser = create_cloud_fuse() File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\cloud_storage.py", line 155, in create_cloud_fuse config = load_from_yaml_file(fname) File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 259, in load_from_yaml_file with exclusive_open_to_read(file_name, 'r') as fp: File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 108, in exclusive_open_to_read lock_fd = acquireLock(op.join('/tmp', File "C:\Users\Caelen\anaconda3\envs\git\lib\site-packages\azfuse\common.py", line 181, in acquireLock import fcntl ModuleNotFoundError: No module named 'fcntl'

There are indeed too many problems under windows, so I switched to Linux later.
About the fcntl， I had the same problem before. My workaround is as follows：

Create the fcntl.py file in the Lib folder of the python installation directory you are using.
The contents of fcntl.py are as follows:

#fcnt1.py

DN_ACCESS = 1
DN_ATTRIB = 32
DN_CREATE = 4
DN_DELETE = 8
DN_MODIFY = 2
DN_MULTISHOT = 2147483648
DN_RENAME = 16

FASYNC = 8192

FD_CLOEXEC = 1

F_ADD_SEALS = 1033

F_DUPFD = 0

F_DUPFD_CLOEXEC = 1030

F_EXLCK = 4
F_GETFD = 1
F_GETFL = 3
F_GETLEASE = 1025
F_GETLK = 5
F_GETLK64 = 5
F_GETOWN = 9
F_GETSIG = 11

F_GET_SEALS = 1034

F_NOTIFY = 1026
F_RDLCK = 0

F_SEAL_GROW = 4
F_SEAL_SEAL = 1
F_SEAL_SHRINK = 2
F_SEAL_WRITE = 8

F_SETFD = 2
F_SETFL = 4
F_SETLEASE = 1024
F_SETLK = 6
F_SETLK64 = 6
F_SETLKW = 7
F_SETLKW64 = 7
F_SETOWN = 8
F_SETSIG = 10
F_SHLCK = 8
F_UNLCK = 2
F_WRLCK = 1

LOCK_EX = 2
LOCK_MAND = 32
LOCK_NB = 4
LOCK_READ = 64
LOCK_RW = 192
LOCK_SH = 1
LOCK_UN = 8
LOCK_WRITE = 128

def fcntl(fd, op, arg=0):
return 0

def ioctl(fd, op, arg=0, mutable_flag=True):
if mutable_flag:
return 0
else:
return ""

def flock(fd, op):
return

def lockf(fd, operation, length=0, start=0, whence=0):
return

**Comment by Carlos25130** [comment]
But I looked at the training sample code, and it doesn't seem to be complete, and it doesn't update the model parameters. Do I need to add the full code myself?










At 2022-08-31 02:06:16, "Jianfeng Wang" ***@***.***> wrote:

I see. If you'd like to train the model, the key training code has already been in this repo. That is, how to do the data augmentation, and how to run forward/backward.

**Comment by amsword** [comment]
> But I looked at the training sample code, and it doesn't seem to be complete, and it doesn't update the model parameters. Do I need to add the full code myself? At 2022-08-31 02:06:16, "Jianfeng Wang" ***@***.***> wrote: I see. If you'd like to train the model, the key training code has already been in this repo. That is, how to do the data augmentation, and how to run forward/backward. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Yes. The full code is the standard one which is almost the same for any model training

**Comment by NielsRogge** [comment]
See #34 for easy inference. The model is now part of 🤗 Transformers: https://huggingface.co/docs/transformers/main/en/model_doc/git
