### ISSUE TITLE
GIT to ONNX

### ISSUE THREAD

**Issue by Mohammad-Amin-Asadi** [microsoft/GenerativeImage2Text#62]
Is there anyway that I can convert git model to onnx? I tried 🤗 Optimum but it does not support GIT for auto converting yet.
https://huggingface.co/docs/optimum/en/exporters/onnx/usage_guides/export_a_model

It needs a custom onnx config and I can not figure out what to do exactly for it . 
Thanks for your help .

**Comment by amsword** [comment]
thanks for posting the issue. unfortunately, i have no experience on onnx conversion. would you be able to post the error details? also onnx community may be better for resolving the issue.
