### ISSUE TITLE
Video Captioning and VideoQA results

### ISSUE THREAD

**Issue by ccsasuke** [microsoft/GenerativeImage2Text#7]
Hi,

Are the code and models available for Video Captioning and QA?
Thank you.

**Comment by amsword** [comment]
yes. it supports. Check out the following. Also updated the README about how to run inference on multiple images. 

https://github.com/microsoft/GenerativeImage2Text/blob/bdc455b98a4bc9e20a3900be53d1018b6e8e02f3/generativeimage2text/layers/decoder.py#L846
