### ISSUE TITLE
TextCaps pre-trained models

### ISSUE THREAD

**Issue by amirmk89** [microsoft/GenerativeImage2Text#8]
Hi,

Thank you for releasing this awesome repo.
Will you be releasing models fine-tuned with TextCaps or ST+MJ data?

Thanks!

**Comment by amsword** [comment]
added the textcaps-fine-tuned models for base and large model variants. However, on ST+MJ, we do not have base and large model variants. 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/3356680/188931771-e035ea0f-7c19-4823-b3c9-87feaa4b1340.png">

**Comment by amirmk89** [comment]
Thank you!
