### ISSUE TITLE
Is there any plans to release fintuned model weights??

### ISSUE THREAD

**Issue by BloomBerry** [microsoft/GenerativeImage2Text#9]
Thank you for sharing such a great research. I'm very excited about the research. 
I am wondering if you have any plans for releasing fintuned model weights??
I want to reproduce VL tasks. (such as VQA, etc)

**Comment by tiesanguaixia** [comment]
> Thank you for sharing such a great research. I'm very excited about the research. I am wondering if you have any plans for releasing fintuned model weights?? I want to reproduce VL tasks. (such as VQA, etc)

Hi, do you know how to download the pretrained weights of the released models?

**Comment by amsword** [comment]
@tiesanguaixia  the pretrained checkpoint will be downloaded automatically through azfuse. you can also manually download the weight. checkout the following issue for a reference on the url.

https://github.com/microsoft/GenerativeImage2Text/issues/35
